version: 2

sources:
  - name: financeiro
    description: 'Tabela com os dados do financeiro da empresa'
    schema: postgres
    database: postgres
    loaded_at_field: DATA EMISSAO  # controle de atualização
    freshness:
      - warn_after: {count: 1, period: day} # Manda um aviso caso a tabela não seja atualizada por um dia
      - error_after: {count: 2, period: day} # Gera um erro caso passe dois dias sem atualizar

    tables: 
      - name: tb_ct_receber
        description: 'Tabela de contas a receber da empresa'
        columns: 
          - name: CODIGO_CLIENTE
            description: 'id do cliente'
            tests:
              - not_null: # Garante que não haverá nulos
          - name: DOCUMENTO
            description: 'numero do documento'
          - name: FATURA
            description: 'numero da fatura'
          - name: VALOR
            description: 'valor da nota'
          - name: VALOR_PAGO
            description: 'valor pago pelo cliente'
          - name: DATA_EMISSAO
            description: 'data da emissao da nota'

        